name: Clarification
description: Request that some aspect of the specification be clarified. 
title: "[Clarification]: "
labels: ["question"] #Verified - label exists
body:
- type: markdown
  attributes: 
    value: >
      Request that some aspect of the specification be clarified.
- type: input
  id: specification
  validations:
    required: true
  attributes: 
    label: Specification
    description: What specification / api is the clarification related to? Provide a link to the API class or SPEC document section. 
    placeholder: |
      ex. [Repository](https://github.com/jakartaee/data/blob/main/api/src/main/java/jakarta/data/repository/Repository.java#L27)
- type: textarea
  validations:
    required: true
  attributes:
    label: I need clarification on ...
    value: |
      > Description of the clarification needed.
- type: textarea
  attributes:
    label: Additional information
    value: |
      > Proposed solutions, code examples, ect. 