# This workflow automates the creation of Specification Documents
# which will be copied into https://github.com/jakartaee/specifications

name: Generate specification documentation

on: 
    workflow_dispatch:
        inputs:
            specVersion:
                description: 'Major and Minor level of release. Example: 1.0'
                required: true

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set up JDK 17
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        java-version: 17
        distribution: 'temurin'
        cache: maven
    - name: Generate specification docs
      run: |
        mvn package --file api/pom.xml -Dspec.version=${{ github.event.inputs.specVersion }}
        mvn package --file spec/pom.xml -Drevremark=FINAL -Dspec.version=${{ github.event.inputs.specVersion }}
    - name: Assemble documentation
      run: |
        mkdir documentation/
        cp spec/target/generated-docs/jakarta-data-${{ github.event.inputs.specVersion }}.pdf   documentation/jakarta-data-${{ github.event.inputs.specVersion }}.pdf
        cp spec/target/generated-docs/jakarta-method-name-query-${{ github.event.inputs.specVersion }}.pdf   documentation/jakarta-method-name-query-${{ github.event.inputs.specVersion }}.pdf

        cp spec/target/generated-docs/jakarta-data-${{ github.event.inputs.specVersion }}.html  documentation/jakarta-data-${{ github.event.inputs.specVersion }}.html
        cp spec/target/generated-docs/jakarta-method-name-query-${{ github.event.inputs.specVersion }}.html  documentation/jakarta-method-name-query-${{ github.event.inputs.specVersion }}.html

        cp -r api/target/reports/apidocs/ documentation/apidocs
    - name: Upload documentation
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: Specification Documentation
        path: documentation/
        if-no-files-found: error