# This workflow automates the creation of Specification Documents
# which will be copied into https://github.com/jakartaee/specifications

name: Generate specification documentation

on: 
    workflow_dispatch:
        inputs:
            specVersion:
                description: 'Major and Minor level of release. Example: 1.0'
                required: true

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Set up JDK 17
      uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
      with:
        java-version: 17
        distribution: 'temurin'
        cache: maven
    - name: Generate specification docs
      run: |
        mvn package --file api/pom.xml -Dspec.version=${{ github.event.inputs.specVersion }}
        mvn package --file spec/pom.xml -Drevremark=FINAL -Dspec.version=${{ github.event.inputs.specVersion }}
    - name: Assemble documentation
      run: |
        mkdir documentation/
        cp spec/target/generated-docs/jakarta-data-${{ github.event.inputs.specVersion }}.pdf   documentation/jakarta-data-${{ github.event.inputs.specVersion }}.pdf
        cp spec/target/generated-docs/jakarta-method-name-query-${{ github.event.inputs.specVersion }}.pdf   documentation/jakarta-method-name-query-${{ github.event.inputs.specVersion }}.pdf

        cp spec/target/generated-docs/jakarta-data-${{ github.event.inputs.specVersion }}.html  documentation/jakarta-data-${{ github.event.inputs.specVersion }}.html
        cp spec/target/generated-docs/jakarta-method-name-query-${{ github.event.inputs.specVersion }}.html  documentation/jakarta-method-name-query-${{ github.event.inputs.specVersion }}.html

        cp -r api/target/apidocs/ documentation/apidocs
    - name: Upload documentation
      uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4.3.6
      with:
        name: Specification Documentation
        path: documentation/
        if-no-files-found: error